# Uncomment this line to define a global platform for your project
platform :ios, '15.6'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  firebase_ios_sdk_local_path = ENV['FIREBASE_IOS_SDK_LOCAL_PATH']
  if firebase_ios_sdk_local_path && File.directory?(firebase_ios_sdk_local_path)
    pod 'Firebase/CoreOnly', :path => firebase_ios_sdk_local_path
    pod 'Firebase/Auth', :path => firebase_ios_sdk_local_path
    pod 'Firebase/Firestore', :path => firebase_ios_sdk_local_path
    pod 'FirebaseAppCheckInterop', :path => firebase_ios_sdk_local_path
    pod 'FirebaseAuth', :path => firebase_ios_sdk_local_path
    pod 'FirebaseAuthInterop', :path => firebase_ios_sdk_local_path
    pod 'FirebaseCore', :path => firebase_ios_sdk_local_path
    pod 'FirebaseCoreExtension', :path => firebase_ios_sdk_local_path
    pod 'FirebaseCoreInternal', :path => firebase_ios_sdk_local_path
    pod 'FirebaseFirestore', :path => firebase_ios_sdk_local_path
    pod 'FirebaseFirestoreInternal', :path => firebase_ios_sdk_local_path
    pod 'FirebaseSharedSwift', :path => firebase_ios_sdk_local_path
  end

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
